state_sort:
	gcc -Wall -Werror -Wextra state_sort.c get_string.c -o ../build/Quest_1

state_search:
	gcc -Wall -Werror -Wextra state_search.c get_string.c -lm -o ../build/Quest_2

clear_state:
	gcc -Wall -Werror -Wextra clear_state.c get_string.c -o ../build/Quest_3
